{{- if not .Values.redis.passwordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rctf.fullname" . }}-redis
  labels:
    {{- include "rctf.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ required "redis.password is required" .Values.redis.password | b64enc | quote }}
{{- end }}
